### ISSUE TITLE
Flutter Project

### ISSUE THREAD

**Issue by areeba-farooq** [FirmanKurniawan/Flutter-Projects#13]
Can I contribute to any of one flutter projects?

**Comment by FirmanKurniawan** [comment]
of course

**Comment by areeba-farooq** [comment]
Any requirements? What kind of Flutter project Do I need to create? Do you need only the UI or the backend too?

**Comment by FirmanKurniawan** [comment]
It's up to you, I'm ready to accept anything from you. I'm happy to help you

**Comment by areeba-farooq** [comment]
So kind Thanks :). Can you assign this to me?

**Comment by FirmanKurniawan** [comment]
ok wait
