### ISSUE TITLE
Discussion about the Tile Game

### ISSUE THREAD

**Issue by syedmehtabali** [FirmanKurniawan/Flutter-Projects#27]
Please leave a message I want to discuss about Tile Game

**Comment by syedmehtabali** [comment]
I am getting this error when I am pushing the code

remote: Permission to FirmanKurniawan/Flutter-Projects.git denied to syedmehtabali.
fatal: unable to access 'https://github.com/FirmanKurniawan/Flutter-Projects.git/': The requested URL returned error: 403

can you please guide me.

**Comment by FirmanKurniawan** [comment]
Have you done a git clone? do push with new "branch" then do manual compare & pull using github on web.

**Comment by syedmehtabali** [comment]
> Have you done a git clone? do push with new "branch" then do manual compare & pull using github on web.

thank you I got the issue, and I have created the pull request kindly review and merge it.
And please make sure you are also merging with the main branch so I can get updated work after the pull
